apiVersion: apps/v1
kind: Deployment
metadata:
  name: book-catalog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: book-catalog
  template:
    metadata:
      labels:
        app: book-catalog
    spec:
      containers:
      - name: book-catalog
        image: sireeshasn/book-catalog:latest
        imagePullPolicy: Always
        env:
        - name: PORT
          value: "8081"
        - name: DATABASE_URL
          value: "postgresql://siri:W8xp1hgbyOCc4HZe7nrzkJ5MYSPSj0Hr@dpg-crhvjsjtq21c738477ag-a.oregon-postgres.render.com/week3db"
        ports:
        - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: book-catalog
spec:
  selector:
    app: book-catalog
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8081     # External access port (same as the app port)
      targetPort: 8081 # Target port on the container
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-management
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory-management
  template:
    metadata:
      labels:
        app: inventory-management
    spec:
      containers:
      - name: inventory-management
        image: sireeshasn/inventory-management:latest
        imagePullPolicy: Always
        env:
        - name: PORT
          value: "8082"
        - name: DATABASE_URL
          value: "postgresql://siri:W8xp1hgbyOCc4HZe7nrzkJ5MYSPSj0Hr@dpg-crhvjsjtq21c738477ag-a.oregon-postgres.render.com/week3db"
        ports:
        - containerPort: 8082
---
apiVersion: v1
kind: Service
metadata:
  name: inventory-management
spec:
  selector:
    app: inventory-management
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8082     # External access port (same as the app port)
      targetPort: 8082 # Target port on the container
